# Generated by Django 3.2.9 on 2021-11-17 05:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('task_category', models.CharField(choices=[('Home_task', 'Home Task'), ('Office_task', 'Office Task'), ('MISC', 'Misc')], max_length=11)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 11, 17, 5, 58, 51, 635889))),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
