# Generated by Django 3.2.9 on 2021-11-17 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 7, 10, 59, 948310)),
        ),
    ]
