# Generated by Django 3.2.9 on 2021-11-22 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_api', '0003_auto_20211117_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 10, 51, 50, 483858)),
        ),
    ]
